name: "Dune Query Updater"
description: "Updates all queries provided in changedQueries"
author: "Ben Smith (@bh2smith)"
branding:
  icon: "arrow-up-circle"
  color: "orange"

inputs:
  changedQueries:
    description:
      "Comma separated list of changed queries. Action Exits if no changed
      files."
  duneApiKey:
    description: "Credentials for Dune SDK (must be a PLUS tier subscription!)."
    required: true

outputs:
  output:
    description: "Not sure yet."

runs:
  using: node20
  main: dist/index.js
