name: "Dune Query Updater"
description: "Updates all queries in dir"
author: "Ben Smith (@bh2smith)"

inputs:
  - changedQueries:
    description: "comma separated list of changed queries"
    required: true
    default: "./queries"
  - duneApiKey: "credentials for Dune SDK (must be a PLUS tier subscription!)."
    required: true

outputs:
  output:
    description: "Not sure yet."

runs:
  using: node20
  main: dist/index.js
